# Generated by Django 6.0.4 on 2026-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_en', models.CharField(default='Carry Your', max_length=100)),
                ('hero_title_ar', models.CharField(default='احملي قصتك', max_length=100)),
                ('hero_highlight_en', models.CharField(default='Story.', max_length=80)),
                ('hero_highlight_ar', models.CharField(default='بأناقة.', max_length=80)),
                ('hero_subtitle_en', models.TextField(default='Discover our curated collection of premium bags and accessories crafted for the modern woman.')),
                ('hero_subtitle_ar', models.TextField(default='اكتشفي مجموعتنا المختارة من الحقائب والإكسسوارات الفاخرة للمرأة العصرية.')),
                ('hero_image', models.ImageField(blank=True, help_text='Product/banner image for the hero section (recommended: 600×600px square)', null=True, upload_to='site/')),
                ('hero_badge_en', models.CharField(default='New Collection 2024', max_length=60)),
                ('hero_badge_ar', models.CharField(default='مجموعة 2024 الجديدة', max_length=60)),
                ('stat_products_label', models.CharField(default='Products', help_text='Leave blank to auto-count from DB', max_length=20)),
                ('stat_customers', models.CharField(default='10K+', help_text='e.g. 10K+ — shown as "10K+ Customers"', max_length=20)),
                ('stat_rating', models.CharField(default='4.9', help_text='e.g. 4.9 — shown as "★ 4.9 Rating"', max_length=10)),
                ('promo_active', models.BooleanField(default=True, help_text='Show/hide the promo banner')),
                ('promo_discount_percentage', models.PositiveSmallIntegerField(default=40, help_text='Discount % shown on banner (e.g. 40 → "Up to 40% OFF")')),
                ('promo_title_en', models.CharField(default='New Arrivals', max_length=100)),
                ('promo_title_ar', models.CharField(default='وصل جديد', max_length=100)),
                ('promo_subtitle_en', models.CharField(default="Don't miss our latest collection at special prices.", max_length=200)),
                ('promo_subtitle_ar', models.CharField(default='لا تفوتي مجموعتنا الجديدة بأسعار مميزة.', max_length=200)),
                ('promo_coupon_code', models.CharField(default='WELCOME10', help_text='Coupon code shown on banner', max_length=30)),
                ('promo_image', models.ImageField(blank=True, help_text='Promo banner side image (optional, recommended: 300×300px)', null=True, upload_to='site/')),
                ('featured_title_en', models.CharField(default='Handpicked For You', max_length=100)),
                ('featured_title_ar', models.CharField(default='مختارة لكِ بعناية', max_length=100)),
                ('new_arrivals_title_en', models.CharField(default='New Arrivals', max_length=100)),
                ('new_arrivals_title_ar', models.CharField(default='وصل حديثاً', max_length=100)),
                ('whatsapp_number', models.CharField(default='201212184205', max_length=20)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True)),
                ('instapay_number', models.CharField(blank=True, default='01205951559', max_length=20)),
                ('orange_cash_number', models.CharField(blank=True, default='01223184205', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
