# Generated by Django 6.0.4 on 2026-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_bg_image',
            field=models.ImageField(blank=True, help_text='Full background image for the promo banner (replaces the dark gradient). Recommended: 1280×400px', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_bg_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=60, help_text='Dark overlay on top of bg image (0=none, 100=fully dark). Default: 60'),
        ),
    ]
