# Generated by Django 6.0.4 on 2026-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_promo_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Full background cover image for the Hero section. Recommended: 1920×800px wide landscape', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=75, help_text='Dark overlay on top of hero background (0=transparent, 100=fully dark). Default: 75'),
        ),
    ]
