# Generated by Django 6.0.4 on 2026-04-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_overlay',
            field=models.PositiveSmallIntegerField(default=70, help_text='Hero background overlay darkness 0-100 (default 70). Higher = darker text will be more readable.'),
        ),
    ]
