# Generated by Django 6.0.4 on 2026-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='e.g. Black, Rose Gold, Cream', max_length=50)),
                ('name_ar', models.CharField(help_text='e.g. أسود، ذهبي وردي، كريم', max_length=50)),
                ('hex_code', models.CharField(default='#000000', help_text='Color hex code e.g. #FF5733 — used as a color swatch', max_length=7)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock for this color. 0 = unavailable')),
                ('image', models.ImageField(blank=True, help_text='Optional: product image showing this color variant', null=True, upload_to='products/colors/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'ordering': ['order', 'name_en'],
            },
        ),
    ]
